services:
  - type: web
    name: book-library-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://*.render.com,https://*.vercel.app,https://*.vercel.com"
    
databases:
  - name: book-library-db
    databaseName: book_library
    user: book_user
