"""Add book popularity tracking

Revision ID: 9a385a344ba4
Revises: decb1406ac43
Create Date: 2025-09-03 16:06:37.229725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a385a344ba4'
down_revision: Union[str, Sequence[str], None] = 'decb1406ac43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'is_living',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('authors', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('authors', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('book_reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('book_reviews', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('books', 'language',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('books', 'is_available',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('books', 'total_copies',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('books', 'available_copies',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('books', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('books', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_title'), table_name='books')
    op.drop_index(op.f('isbn'), table_name='books')
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.alter_column('request_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('review_votes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('review_votes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('request_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.create_index(op.f('isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('idx_title'), 'books', ['title'], unique=False)
    op.alter_column('books', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('books', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('books', 'available_copies',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               nullable=True)
    op.alter_column('books', 'total_copies',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               nullable=True)
    op.alter_column('books', 'is_available',
               existing_type=sa.Integer(),
               server_default=sa.text("'1'"),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('books', 'language',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'English'"),
               existing_nullable=True)
    op.alter_column('book_reviews', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('book_reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('authors', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('authors', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('authors', 'is_living',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    # ### end Alembic commands ###
